#!/bin/bash

NEWVERSION=$1
DEPLOYCOPY=$2
DEPLOYDEST=$3
DEPLOYPROJECTNAME=$4
DEPLOYFILENAME=$5
DEPLOYMODE=$6

DEPLOYOUTPUTDIR="../${NEWVERSION}"

echo "cd ${DEPLOYCOPY}"
cd ${DEPLOYCOPY}
echo "cp -f ${DEPLOYFILENAME} ${DEPLOYDEST}"
cp -f ${DEPLOYFILENAME} ${DEPLOYDEST}
echo "cd ${DEPLOYDEST}"
cd ${DEPLOYDEST}
echo "mkdir -p ${DEPLOYDEST}/${DEPLOYOUTPUTDIR}"
mkdir -p ${DEPLOYDEST}/${DEPLOYOUTPUTDIR}
echo "tar -zxvf ${DEPLOYFILENAME} -C ${DEPLOYOUTPUTDIR}"
tar -zxvf ${DEPLOYFILENAME} -C ${DEPLOYDEST}/${DEPLOYOUTPUTDIR}
echo "ln -sf ${DEPLOYOUTPUTDIR} ${DEPLOYDEST}/../current"
ln -sfT ${DEPLOYDEST}/${DEPLOYOUTPUTDIR} ${DEPLOYDEST}/../current

echo "cd ${DEPLOYDEST}/../current"
cd ${DEPLOYDEST}/../current

if [ ${DEPLOYMODE} = "PRODUCTION" ]; then
  //echo "make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRODUCTION='TRUE'"
  //make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRODUCTION='TRUE'
elif [ ${DEPLOYMODE} = "PRELEASE" ]; then
  //echo "make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRELEASE='TRUE'"
  //make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRELEASE='TRUE'
fi

